require: rubocop-performance

AllCops:
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - bin/**/*
    - vendor/assets/**/*
    - vendor/bundle/**/*

Layout/EmptyLines:
  Exclude:
    - config/initializers/sorcery.rb

Layout/ExtraSpacing:
  Exclude:
    - db/migrate/**/*

Layout/IndentationConsistency:
  EnforcedStyle: rails
  Exclude:
    - config/routes.rb

Layout/SpaceBeforeFirstArg:
  Exclude:
    - config/routes.rb

Lint/Debugger:
  AutoCorrect: False

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StructInheritance:
  Exclude:
    - app/policies/**/*

Style/ClassVars:
  Exclude:
    - app/controllers/concerns/auth.rb
    - app/controllers/v1/images_controller.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*
  Max: 20

Metrics/LineLength:
  Max: 120
  Exclude:
    - Rakefile
    - config/**/*
    - lib/tasks/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - lib/tasks/auto_annotate_models.rake
    - config/routes.rb
    - config/initializers/sorcery.rb

Metrics/ClassLength:
  Exclude:
    - test/controllers/v1/pins_controller_test.rb
    - test/controllers/v1/assortments_controller_test.rb
    - test/controllers/v1/collections_controller_test.rb
    - test/controllers/v1/images_controller_test.rb

Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Rails/NotNullColumn:
  Exclude:
    - db/migrate/20190501020226_auth0_support.rb # All users are deleted in this migration so the default isn't bad.

Rails/FilePath:
  Exclude:
    - config/initializers/apipie.rb