branch-defaults:
  develop:
    environment: PinsterApi-1
  master:
    environment: PinsterApi-prod
environment-defaults:
  PinsterApi-1:
    branch: null
    repository: null
  PinsterApi-prod:
    branch: null
    repository: null
global:
  application_name: PinsterApi
  default_ec2_keyname: PinsterApi
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Puma with Ruby 2.4
    running on 64bit Amazon Linux/2.7.2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
